# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 68a01230a06002d21483cb40bf6e9b978c6252142607f2e1c0e4329d7f6a6d2925f7715dc5bc05dc77f1c33dcac49cd3a80586329350d7633a17d5fb9b41f928

test:
  secret_key_base: 3167cf198d99cbcc1dda6091e45b8097c7bd61971e76b7c0be02d4df6e2a313a710bd2c0beb6f6b1380230747578d4c79f9901ee8fd6278d5d4d8b9214f3d124

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
